In [2]:
##importing numpy
import numpy as np

In [7]:
##making one 1D array
arr1= np.array([1,2,3,4,5])
print(arr1)

#type and shape
print(type(arr1))
print(arr1.shape)

#single dimension array is []
#2D would be [[]]

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
#reshaping
arr2=arr1
arr2.reshape(1,5) #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [10]:
#2D array
arr2D = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2D)
print(arr2D.shape) # 2rows and 5columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [15]:
#creating random arrays
np.arange(0,10,2)
#arange(start,end,skip)

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
#generating arrays
eg1 = np.ones((3,4)) #generates arrays with all (1) in (rows, columns)
print(eg1)

eg2 = np.eye(3) #identity matrix
print(eg2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#Attributes of numpy
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr) #printing array
print(arr.shape) #(rows,columns)
print(arr.ndim) #prints dimensions of array
print(arr.size) #total elements in array
print(arr.dtype) #array datatype
print(arr.itemsize) #print bytes used

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2
10
int64
8


In [23]:
#Numpy Vectorized operations (element wise)
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print(arr1 + arr2) #element wise addition
print(arr1 - arr2) #element wise subtraction
print(arr1 * arr2) #element wise multiplication
print(arr1 / arr2) #element wise division


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [25]:
#Universal function (applies to entire array)
arr=np.array([1,2,3,4,5,6])

print(np.sqrt(arr)) #square root
print(np.exp(arr)) #exponential function
print(np.sin(arr)) #sine function
print(np.log) #natural log

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
<ufunc 'log'>


In [42]:
#slicing and indexing
arr=np.array([[1,2,3,4,5], [10,20,30,40,50], [100,200,300,400,500]])

element =arr[1][3] #retreiving 40 out of the 2D array
print(element)

mini_matrix = arr[1:,2:4]  #retrieving a matrix from the bigger matrix itself
#arr[row begining:row ending (blank for last ), [coloumn begining: column ending]] eg [1:3, 2:]
print(mini_matrix)

40
[[ 30  40]
 [300 400]]


In [49]:
#modifying the elements
arr[0][0] = 111111
print(arr)

[[111111      2      3      4      5]
 [    10     20     30     40     50]
 [   100    200    300    400    500]]


In [53]:
#Normalisation - CHanging data to have mean of 0 and standard deviation of 1
mean = np.mean(arr)
std = np.std(arr)
normalized_data = (arr - mean) / std
print(normalized_data)

[[ 3.74159917 -0.27147777 -0.27144166 -0.27140554 -0.27136942]
 [-0.27118883 -0.27082764 -0.27046646 -0.27010528 -0.26974409]
 [-0.26793817 -0.26432634 -0.2607145  -0.25710266 -0.25349082]]


In [56]:
#Stats method
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
var = np.var(arr)
print(f"Mean = {mean}\nMedian = {median}\nStd Dev = {std}\nVariance = {var}")

Mean = 7518.333333333333
Median = 40.0
Std Dev = 27686.735492329582
Variance = 766555322.2222226


In [64]:
#logical operation
data = np.arange(0,10)
print(data)
print((data>=5) & (data<=8)) #here logical symbol of & will work and not "and"

[0 1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True False]
